/**
 * Canonical ActorContext (Capability 0.8, Slice 0.8.1).
 *
 * The single request-scoped, immutable identity+authorization value every
 * protected LawME operation will consume: routes, application use-cases,
 * repository scoping, Audit/Activity attribution, Matter Bootstrap, Workflow,
 * and AI permission checks.
 *
 * Identity keys (from the real schema):
 *   - `profileId`  = public.profiles.id — THE canonical LawME actor id used by
 *                    domain tables. (profiles.id references auth.users.id, so for
 *                    a user it equals the auth id, but it is referenced as the
 *                    profile id everywhere in the domain.)
 *   - `authUserId` = auth.users.id — authentication identity ONLY.
 *   - `membership.id` = organization_memberships.id — kept distinct from profile.
 * Email / display name are NEVER identity keys and are absent here.
 *
 * ActorContext carries NO access/refresh token, JWT, cookie, email, or provider
 * credential.
 */
import type { Capability } from "./capabilities.ts";
import type { OrganizationRole } from "./role-capabilities.ts";

export type ActorType = "user" | "system" | "service";

/** The fully-resolved context for a real authenticated HUMAN actor. */
export interface ActorContext {
  readonly actor: {
    readonly type: "user";
    /** public.profiles.id — the canonical domain actor id. */
    readonly profileId: string;
    /** auth.users.id — authentication identity only (equals profileId for users). */
    readonly authUserId: string;
  };
  readonly organization: {
    readonly id: string;
  };
  readonly membership: {
    readonly id: string;
    readonly role: OrganizationRole;
    readonly status: "active";
  };
  readonly capabilities: ReadonlySet<Capability>;
  readonly policy: {
    readonly capabilityMapVersion: string;
    readonly authorizationPolicyVersion: string;
  };
  readonly request: {
    readonly correlationId: string;
    readonly sessionId?: string;
  };
}

/**
 * Explicit non-human actor contract: a LawME-controlled automated process
 * (retention cleanup, scheduled recomputation, notifications). Has an EXPLICIT
 * identifier and is never a fake human profile. Contract only in this slice —
 * background-job infrastructure is not built here.
 */
export interface SystemActor {
  readonly type: "system";
  /** Explicit, stable system-process identifier, e.g. "retention-cleanup". */
  readonly systemId: string;
}

/**
 * Explicit infrastructure execution identity. A service actor is NOT a human and
 * is NOT automatically authorized for any business action; its presence never
 * substitutes for an originating human/system authorization context.
 */
export interface ServiceActor {
  readonly type: "service";
  /** Explicit, stable service identifier, e.g. "matter-storage". */
  readonly serviceId: string;
}

/**
 * Trusted input for the resolver. This value may be constructed ONLY by trusted
 * server code (e.g. after a verified session in a later slice). It is NOT a
 * client DTO: a browser must never be able to assert `authUserId`,
 * `requestedOrganizationId`, capabilities, role, or membership.
 */
export interface TrustedIdentityInput {
  /** Verified authentication identity (auth.users.id). Server-trusted only. */
  readonly authUserId: string;
  /** Optional organization the actor wishes to act in; validated against membership. */
  readonly requestedOrganizationId?: string;
  /** Optional internal correlation id; validated/regenerated by the resolver. */
  readonly correlationId?: string;
  /** Optional opaque session id (non-secret) for correlation only. */
  readonly sessionId?: string;
}
