-- ============================================================================
-- LawME — Capability 2 · Slice 2A (Part 2): Intake Draft persistence
--   New table: matter_intake_drafts
--
-- STATUS: APPLIED TO DEVELOPMENT.  (historically reconciled — see below)
--   Applied to:        DEVELOPMENT project  udispadsbxqicmawqcuk  ONLY.
--   Migration version: 20260716120000
--   Applied body:      exactly the SQL in THIS file (executable body below).
--   Original executed  SHA-256 of the full file as executed:
--     f01801494ad3c8d1ca822747b2516e44123c498a8a8a24de36c70d53ad4f0e5e
--     (executable body identical to this file; only non-executable header
--      comments were later corrected during reconciliation — the executable
--      SQL is byte-for-byte the originally-executed artifact.)
--   Production:        NEVER touched.
--
--   HISTORICAL ACCURACY NOTE (reconciliation, 2026-07-21)
--     The INSERT policy below uses `created_by = auth.uid()` — the EXACT form
--     originally executed against Development. An out-of-band ALTER later
--     rewrote it to `(select auth.uid())` for the auth_rls_initplan advisor;
--     that correction was NOT part of this migration and has been REMOVED from
--     this historical file. It is recorded properly in the additive migration
--     20260717090000_capability2_slice2a_intake_drafts_hardening.sql, so the
--     remote schema is once again fully represented by migration history.
--     Do NOT edit this file to pretend the InitPlan fix (or any later
--     hardening) originated here.
--
--   v2 (post access-model review): the first draft scoped access with generic
--   app.is_org_member, which would have let EVERY organization member read a
--   confidential pre-Matter draft. Corrected to CREATOR + EXPLICIT-REVIEWER
--   scoping, a constrained DELETE, and the approved status lifecycle. This
--   CREATOR + EXPLICIT-REVIEWER form IS what was applied to Development.
--
-- WHY (audit result)
--   Intelligent Intake produces a reviewable MatterIntakeDraft that must SURVIVE
--   refresh and a new session before the attorney confirms creation. No applied
--   table can represent it, and matters / matter_notes must NOT be misused for
--   draft storage.
--
-- ACCESS MODEL (frozen)
--   * Creator (created_by = auth.uid()): full access.
--   * Explicit reviewer (auth.uid() listed in reviewer_ids): access only when
--     explicitly assigned. Reviewers are added by the creator/server; approved
--     reviewer roles (partner / senior_lawyer / compliance) are granted by
--     assignment — there is no pre-Matter org-role source for them, so explicit
--     assignment is the smallest safe model.
--   * Other organization members: NO access (generic org membership is NOT
--     sufficient for a confidential draft).
--   * Anonymous: NO access. Service role: server only, bypasses RLS.
--
-- CONFIDENTIAL INPUT — HONEST BOUNDARY
--   `confidential_input` stores the raw story/pasted text so the draft-review
--   experience survives refresh. It is protected by (a) RLS creator/reviewer
--   scoping and (b) Supabase's managed AT-REST disk encryption. There is NO
--   application-level / column-level encryption in this Part — this comment does
--   not claim one. Raw input is NEVER written to logs, URLs, Activity, or Audit
--   payloads. No chain-of-thought or provider hidden reasoning is ever stored.
--
-- RETENTION / DELETE
--   Drafts are deletable ONLY when abandoned (status='expired' by the retention
--   job) or 'rejected', never while confirmed-linked (confirmed_matter_id set),
--   and only by an authorized actor in the same tenant. Deleting a draft can
--   NEVER cascade into Matter content (confirmed_matter_id is a plain FK).
--
-- SINGLE TRANSACTION: any failure during apply rolls back automatically.
-- ============================================================================

begin;

-- Creator/explicit-reviewer access predicate. SECURITY DEFINER so it can read
-- membership without recursive RLS; still tenant-fenced via app.is_org_member.
create or replace function app.can_access_intake_draft(draft_org uuid, draft_creator uuid, reviewers uuid[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select app.is_org_member(draft_org)
     and (auth.uid() = draft_creator
          or auth.uid() = any(coalesce(reviewers, '{}'::uuid[])));
$$;

-- Org-consistency: a draft's confirmed_matter_id (when set) must belong to the
-- SAME organization. SECURITY DEFINER so a cross-tenant id is rejected.
create or replace function app.enforce_draft_matter_org()
returns trigger
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  matter_org uuid;
begin
  if new.confirmed_matter_id is null then
    return new;
  end if;
  select m.organization_id into matter_org from public.matters m where m.id = new.confirmed_matter_id;
  if matter_org is null then
    raise exception 'matter % does not exist', new.confirmed_matter_id using errcode = 'foreign_key_violation';
  end if;
  if new.organization_id <> matter_org then
    raise exception 'cross-tenant confirmed_matter_id rejected: draft org %, matter org %',
      new.organization_id, matter_org using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

create table public.matter_intake_drafts (
  id                          uuid primary key default gen_random_uuid(),
  organization_id             uuid not null references public.organizations (id),
  -- the creator: authorized for full access. Required for authenticated inserts.
  created_by                  uuid references public.profiles (id),
  -- explicitly-assigned reviewers (partner / senior_lawyer / compliance, by
  -- assignment). Only these + the creator may access the draft.
  reviewer_ids                uuid[] not null default '{}'::uuid[],
  -- approved lifecycle.
  status                      text not null default 'active' check (status in
                                ('active','needs_clarification','ready_for_review',
                                 'confirming','confirmed','rejected','expired')),
  provider_mode               text not null default 'deterministic' check (provider_mode in
                                ('deterministic','model_assisted','production_disabled')),
  engine_version              text not null,
  version_token               text not null,           -- optimistic concurrency / stale detection
  policy_snapshot             jsonb not null default '{}'::jsonb, -- confidentiality + ai_policy at review time
  structured_draft            jsonb not null,          -- normalized MatterIntakeDraft (never a confirmed fact)
  review_state                jsonb not null default '{}'::jsonb, -- per-item approved/edited/rejected
  clarification_rounds        jsonb not null default '[]'::jsonb,
  provenance                  jsonb not null default '[]'::jsonb, -- rule/extraction/provider metadata ONLY
  confidential_input          text,                    -- raw input; RLS-isolated; never logged
  confirmation_idempotency_key text,                   -- one confirmation per (org, key)
  confirmed_matter_id         uuid references public.matters (id), -- the Matter a confirmed draft produced
  correlation_id              uuid,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  expires_at                  timestamptz              -- retention: abandoned drafts → 'expired' → deletable
);

create index matter_intake_drafts_org_status_idx on public.matter_intake_drafts (organization_id, status);
create index matter_intake_drafts_org_creator_idx on public.matter_intake_drafts (organization_id, created_by);
create index matter_intake_drafts_expires_idx on public.matter_intake_drafts (expires_at) where expires_at is not null;
-- idempotency guard: one confirmation per (org, key); NULL keys are exempt.
create unique index matter_intake_drafts_idem_uq
  on public.matter_intake_drafts (organization_id, confirmation_idempotency_key)
  where confirmation_idempotency_key is not null;

create trigger matter_intake_drafts_touch before update on public.matter_intake_drafts
  for each row execute function app.touch_updated_at();
create trigger matter_intake_drafts_org_consistent
  before insert or update on public.matter_intake_drafts
  for each row execute function app.enforce_draft_matter_org();

-- ============================================================================
-- RLS — deny-by-default. Access is CREATOR + EXPLICIT REVIEWER only (not
-- generic org membership). Trusted server writes use service_role (bypasses
-- RLS); these authenticated policies are the client-facing wall.
-- ============================================================================
alter table public.matter_intake_drafts enable row level security;

-- read: creator or an explicitly-assigned reviewer (same tenant).
create policy matter_intake_drafts_select on public.matter_intake_drafts
  for select to authenticated
  using (app.can_access_intake_draft(organization_id, created_by, reviewer_ids));

-- create: an org member creating their OWN draft (created_by must be the actor).
create policy matter_intake_drafts_insert on public.matter_intake_drafts
  for insert to authenticated
  with check (app.is_org_member(organization_id) and created_by = auth.uid());

-- update: creator or assigned reviewer, before and after.
create policy matter_intake_drafts_update on public.matter_intake_drafts
  for update to authenticated
  using (app.can_access_intake_draft(organization_id, created_by, reviewer_ids))
  with check (app.can_access_intake_draft(organization_id, created_by, reviewer_ids));

-- delete: authorized actor, deletable status only, NEVER a confirmed-linked draft.
create policy matter_intake_drafts_delete on public.matter_intake_drafts
  for delete to authenticated
  using (
    (app.can_access_intake_draft(organization_id, created_by, reviewer_ids)
      or app.is_org_admin(organization_id))
    and status in ('rejected', 'expired')
    and confirmed_matter_id is null
  );

commit;

-- ============================================================================
-- ROLLBACK GUIDANCE (safe on a DB holding no real drafts):
--   begin;
--   drop table if exists public.matter_intake_drafts cascade;
--   drop function if exists app.enforce_draft_matter_org();
--   drop function if exists app.can_access_intake_draft(uuid, uuid, uuid[]);
--   commit;
-- Capability 1 + Slice 2 tables and all else are untouched by this migration.
-- ============================================================================
