-- data.gov.il legal-dataset qualification — registry correction (idempotent).
update legalai.legal_sources ls set
  collector_status = v.cstatus, audit_status = v.astatus,
  legal_reuse_status = case when v.verdict='OPEN_WITH_OBLIGATIONS' then 'open_license'
                            when v.verdict='VERIFIED_OPEN' then 'open_license'
                            when v.verdict='REJECTED' then 'restricted' else 'unknown' end,
  audit_notes = 'QUAL '||v.verdict||' | tier'||v.tier||' | '||v.category||' | '||v.content||' | '||v.note,
  priority_score = v.prio, last_audited_at = now()
from (values
  ('data_gov_il:ararim', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 1, 'tribunal_decisions', 'full_documents', 'החלטות בתי הדין לעררים — CSV + PDF מלאים', 80),
  ('data_gov_il:mishmoret', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 1, 'tribunal_decisions', 'full_documents', 'החלטות בתי הדין למשמורת — CSV + PDF מלאים', 80),
  ('data_gov_il:judgments', 'ready_to_build', 'completed', 'VERIFIED_OPEN', 1, 'court_metadata', 'metadata_plus_summary', 'פסקי דין חופש-מידע 2021 — מס'' הליך, צדדים, מחוז, תמצית, הוצאות', 80),
  ('data_gov_il:ica_companies', 'ready_to_build', 'completed', 'VERIFIED_OPEN', 2, 'company_registry', 'registry_records', 'רשם החברות — רשומות', 55),
  ('data_gov_il:ica-changes', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'company_registry', 'registry_records', 'רשם החברות — שינויים', 55),
  ('data_gov_il:ica_partnerships', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'company_registry', 'registry_records', 'רשם השותפויות', 55),
  ('data_gov_il:membership-in-liquidation', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'company_registry', 'registry_records', 'חברות בפירוק', 55),
  ('data_gov_il:moj-amutot', 'ready_to_build', 'completed', 'VERIFIED_OPEN', 2, 'nonprofit_registry', 'registry_records', 'רשם העמותות', 55),
  ('data_gov_il:simaneymisahr', 'ready_to_build', 'completed', 'VERIFIED_OPEN', 2, 'trademarks', 'registry_records', 'בקשות סימני מסחר', 55),
  ('data_gov_il:mamtziim_patents', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'patents', 'registry_records', 'ממציאים — בקשות פטנט', 55),
  ('data_gov_il:halicim_bateydin', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'patents', 'registry_records', 'הליכים ברשם הפטנטים', 55),
  ('data_gov_il:yerusha', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'inheritance', 'registry_records', 'רשם לענייני ירושה', 55),
  ('data_gov_il:hekdeshot', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'inheritance', 'registry_records', 'הקדשות ציבוריים', 55),
  ('data_gov_il:mashkonot', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'legal_reference', 'registry_records', 'רשם המשכונות', 55),
  ('data_gov_il:britzugiyut', 'ready_to_build', 'completed', 'OPEN_WITH_OBLIGATIONS', 2, 'legal_reference', 'registry_records', 'מרשם ברית הזוגיות', 55),
  ('data_gov_il:regulationdatabase', 'ready_to_build', 'completed', 'VERIFIED_OPEN', 2, 'regulation', 'reference', 'מאגר רגולציה (חוק עקרונות האסדרה)', 55),
  ('data_gov_il:takanot_hayerusha-batei_hadin_hasharaim', 'ready_to_build', 'completed', 'VERIFIED_OPEN', 2, 'inheritance', 'metadata_plus_summary', 'בקשות צו ירושה — בתי הדין השרעיים', 55),
  ('data_gov_il:takanot_hayerusha-batei_hadin_hadruzim', 'ready_to_build', 'completed', 'VERIFIED_OPEN', 2, 'inheritance', 'metadata_plus_summary', 'בקשות צו ירושה — בתי הדין הדרוזיים', 55),
  ('data_gov_il:trademarks_nice', 'audit_required', 'completed', 'VERIFIED_OPEN', 3, 'trademarks', 'reference', 'סיווגי ניס לסימני מסחר', 30),
  ('data_gov_il:bakashot_cpc', 'audit_required', 'completed', 'OPEN_WITH_OBLIGATIONS', 3, 'patents', 'reference', 'סיווגי CPC לפטנטים', 30),
  ('data_gov_il:tovin', 'audit_required', 'completed', 'OPEN_WITH_OBLIGATIONS', 3, 'legal_reference', 'reference', 'רשימת סחורות/שירותים', 30),
  ('data_gov_il:maale', 'audit_required', 'completed', 'VERIFIED_OPEN', 3, 'legal_reference', 'reference', 'כלי חיפוש קטן', 30),
  ('data_gov_il:magistrate-court-list', 'audit_required', 'completed', 'VERIFIED_OPEN', 3, 'court_metadata', 'directory', 'רשימת בתי משפט השלום', 30),
  ('data_gov_il:court-lost', 'audit_required', 'completed', 'VERIFIED_OPEN', 3, 'court_metadata', 'directory', 'רשימת בתי משפט ובתי דין לעבודה', 30),
  ('data_gov_il:molsa-court-assiatance-units', 'audit_required', 'completed', 'VERIFIED_OPEN', 3, 'directory_only', 'directory', 'יחידות סיוע ליד בתי המשפט', 30),
  ('data_gov_il:my-bills', 'audit_required', 'manual_review_required', 'REVIEW', 0, 'legislation', 'reference', 'הצעות חוק — קישור חיצוני (רישיון עשוי לא לחול)', 15),
  ('data_gov_il:odata', 'audit_required', 'manual_review_required', 'REVIEW', 0, 'legislation', 'reference', 'מידע פרלמנטרי — קישור חיצוני', 15),
  ('data_gov_il:547', 'audit_required', 'manual_review_required', 'REVIEW', 0, 'legislation', 'none', 'אין resources נגישים', 15),
  ('data_gov_il:accessibilityorders', 'audit_required', 'manual_review_required', 'REVIEW', 0, 'administrative_decisions', 'unclear', 'צווי נגישות — טרם אומת תוכן', 15),
  ('data_gov_il:supervisionfiles', 'audit_required', 'manual_review_required', 'REVIEW', 0, 'unclear', 'unclear', 'קבצי פיקוח — טרם אומת תוכן', 15),
  ('data_gov_il:ransom', 'audit_required', 'manual_review_required', 'REVIEW', 0, 'unclear', 'unclear', 'טרם אומת תוכן משפטי', 15),
  ('data_gov_il:businessreq', 'audit_required', 'manual_review_required', 'REVIEW', 0, 'unclear', 'unclear', 'דרישות עסק — טרם אומת', 15),
  ('data_gov_il:crime_records_data', 'retired', 'completed', 'REJECTED', 0, 'statistical_only', 'statistics', 'סטטיסטיקת פשיעה — לא מסמכים משפטיים', 0),
  ('data_gov_il:releasespeed', 'retired', 'completed', 'REJECTED', 0, 'statistical_only', 'statistics', 'זמני שחרור מכס — סטטיסטי', 0),
  ('data_gov_il:stream-monitoring', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'ניטור נחלים', 0),
  ('data_gov_il:sewage_budgeting', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'תקצוב ביוב', 0),
  ('data_gov_il:noise-duration', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'רעש', 0),
  ('data_gov_il:budget2020', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'תקציב', 0),
  ('data_gov_il:metrology', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'מטרולוגיה', 0),
  ('data_gov_il:stat2017', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'סטטיסטיקת ספורט', 0),
  ('data_gov_il:stat2018', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'סטטיסטיקת ספורט', 0),
  ('data_gov_il:firefightingfees', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'reference', 'אגרות כבאות', 0),
  ('data_gov_il:n2r', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'בטיחות בדרכים', 0),
  ('data_gov_il:goverment-domesticdebt', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'חוב ממשלתי', 0),
  ('data_gov_il:data-doctionary-business', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'reference', 'מילון נתונים', 0),
  ('data_gov_il:data-dictionary-asset', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'reference', 'מילון נתונים', 0),
  ('data_gov_il:2023', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'none', 'ללא תוכן משפטי', 0),
  ('data_gov_il:continuing_education', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'reference', 'השתלמויות', 0),
  ('data_gov_il:sherut-mivhan-lanoar', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'reference', 'שירות מבחן לנוער — מנהלי', 0),
  ('data_gov_il:manager-elections-2023', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'בחירות', 0),
  ('data_gov_il:mfa_un', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'reference', 'או"ם', 0),
  ('data_gov_il:aluyot-pituach', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'עלויות פיתוח', 0),
  ('data_gov_il:business-licensing-br7', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'reference', 'רישוי עסקים — רשימה', 0),
  ('data_gov_il:unified_businesses-br7', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'reference', 'עסקים — רשימה', 0),
  ('data_gov_il:companiespersonscleansing20200', 'retired', 'completed', 'REJECTED', 0, 'directory_only', 'reference', 'ניקוי כפילויות — טכני', 0),
  ('data_gov_il:566', 'retired', 'completed', 'REJECTED', 0, 'not_legal', 'statistics', 'סטטיסטיקה', 0)
) as v(code,cstatus,astatus,verdict,tier,category,content,note,prio)
where ls.code = v.code;
